stages: [build_and_push, deploy]

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: "1"
  DOCKER_HOST: tcp://docker:2375

  ECR_URL: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  IMAGE: "$ECR_URL/$ECR_REPO"

build_and_push:
  stage: build_and_push
  image: docker:26
  services:
    - name: docker:26-dind
      alias: docker
      command: ["--mtu=1450"]
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_URL"
    - docker system prune -af || true
    - docker builder prune -af || true
    - docker image prune -af || true
  script:
    - echo "VITE_API_BASE_URL=$VITE_API_BASE_URL"
    - docker build --build-arg VITE_API_BASE_URL="$VITE_API_BASE_URL" -t "$IMAGE:$CI_COMMIT_SHORT_SHA" -t "$IMAGE:latest" -f Dockerfile .
    - docker push "$IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$IMAGE:latest"
  only:
    - main
    - master

deploy_to_github:
  stage: deploy
  image: alpine:3.20
  needs: ["build_and_push"]
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts
    - git config --global user.email "ci-bot@your-org"
    - git config --global user.name "GitLab CI"
  script:
    - git clone --mirror "$CI_REPOSITORY_URL" mirror.git
    - cd mirror.git
    - git remote add github "$GITHUB_REPO_SSH"
    - git push --mirror github
  only:
    - main
    - master