name: Build React

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Instalar dependências
        run: yarn install --frozen-lockfile
      - name: Build do projeto
        run: yarn build

  mirror:
    name: Mirror para GitLab (via SSH)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Carregar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Registrar host key do GitHub e GitLab (8822)
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan github.com 2>/dev/null | tee -a ~/.ssh/known_hosts >/dev/null
          ssh-keyscan -p 8822 tools.ages.pucrs.br 2>/dev/null | tee -a ~/.ssh/known_hosts >/dev/null
      - name: Clonar repositório de origem como espelho (GitHub)
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=yes"
        run: |
          git clone --mirror "git@github.com:${{ github.repository }}.git" mirror.git
      - name: Adicionar remoto GitLab e push --mirror
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=yes -p 8822"
        run: |
          cd mirror.git
          git remote add gitlab "${{ secrets.GITLAB_REPO_SSH }}"
          git push --mirror gitlab