name: Build React

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Build do projeto
        run: yarn build

  mirror:
    name: Mirror para GitLab (via SSH)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout (histórico completo + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true

      - name: Carregar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Registrar host key do GitLab (porta 8822)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 8822 tools.ages.pucrs.br >> ~/.ssh/known_hosts

      - name: Adicionar remoto GitLab (SSH)
        run: |
          git remote add gitlab "ssh://git@tools.ages.pucrs.br:8822/plataforma-de-doa-es-para-o-p-o-dos-pobres/front-end.git"

      - name: Sincronizar refs e espelhar (push --mirror)
        run: |
          git fetch --prune --tags origin
          git push --mirror gitlab